/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import Enums.TipoDependencia;
import Enums.TipoEstado;
import Enums.TipoExpediente;
import modelos.Expediente;

/**
 *
 * @author hecto
 */
public class ExpedienteInfo extends javax.swing.JFrame {

    /**
     * Creates new form Expediente
     */
    private Expediente expediente;

    public ExpedienteInfo(Expediente expediente) {
        initComponents();
        this.expediente = expediente;
        System.out.println(this.expediente.getAsunto());
        areaDescripcion.setText(TipoDependencia.fromEnumToString(this.expediente.getTipoDependencia()));
        asuntoDescripcion.setText("".equals(this.expediente.getAsunto()) ? "No asunto ingresado" : this.expediente.getAsunto());
        estadoActualDescripcion.setText(TipoEstado.fromEnumToString(this.expediente.getEstado()));
        tipoExpedienteDescripcion.setText(TipoExpediente.fromEnumToString(this.expediente.getTipoExpediente()));
        documentoDescripcion.setText(this.expediente.getDocumentoReferencia() == null ? "No documento ingresado" : this.expediente.getDocumentoReferencia().getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        area = new javax.swing.JLabel();
        tipoExpediente = new javax.swing.JLabel();
        estadoActual = new javax.swing.JLabel();
        estadoActualDescripcion = new javax.swing.JLabel();
        tipoExpedienteDescripcion = new javax.swing.JLabel();
        areaDescripcion = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        asuntoDescripcion = new javax.swing.JLabel();
        documentoDescripcion = new javax.swing.JLabel();
        asunto1 = new javax.swing.JLabel();
        documentoReferencia1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Información ingresada");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Proceso:");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        area.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        area.setForeground(new java.awt.Color(255, 255, 255));
        area.setText("Área en la que se encuentra: ");

        tipoExpediente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tipoExpediente.setForeground(new java.awt.Color(255, 255, 255));
        tipoExpediente.setText("Tipo de expediente: ");

        estadoActual.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        estadoActual.setForeground(new java.awt.Color(255, 255, 255));
        estadoActual.setText("Estado actual:");

        estadoActualDescripcion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        estadoActualDescripcion.setForeground(new java.awt.Color(255, 255, 255));
        estadoActualDescripcion.setText("estadoActualDescripcion");

        tipoExpedienteDescripcion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tipoExpedienteDescripcion.setForeground(new java.awt.Color(255, 255, 255));
        tipoExpedienteDescripcion.setText("tipoExpedienteDescripcion");

        areaDescripcion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        areaDescripcion.setForeground(new java.awt.Color(255, 255, 255));
        areaDescripcion.setText("areaDescripcion");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(area)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(areaDescripcion))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(estadoActual)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(estadoActualDescripcion))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tipoExpediente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tipoExpedienteDescripcion)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(estadoActual)
                    .addComponent(estadoActualDescripcion))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipoExpediente)
                    .addComponent(tipoExpedienteDescripcion))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(area)
                    .addComponent(areaDescripcion))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        asuntoDescripcion.setBackground(new java.awt.Color(255, 255, 255));
        asuntoDescripcion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        asuntoDescripcion.setForeground(new java.awt.Color(255, 255, 255));
        asuntoDescripcion.setText("AsuntoDescripcion");

        documentoDescripcion.setBackground(new java.awt.Color(255, 255, 255));
        documentoDescripcion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        documentoDescripcion.setForeground(new java.awt.Color(255, 255, 255));
        documentoDescripcion.setText("documentoReferenciaDescripcion");

        asunto1.setBackground(new java.awt.Color(255, 255, 255));
        asunto1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        asunto1.setForeground(new java.awt.Color(255, 255, 255));
        asunto1.setText("Asunto:");

        documentoReferencia1.setBackground(new java.awt.Color(255, 255, 255));
        documentoReferencia1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        documentoReferencia1.setForeground(new java.awt.Color(255, 255, 255));
        documentoReferencia1.setText("Documento de referencia:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(asunto1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(asuntoDescripcion))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(documentoReferencia1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(documentoDescripcion)))
                .addContainerGap(262, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(asuntoDescripcion)
                    .addComponent(asunto1))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(documentoReferencia1)
                    .addComponent(documentoDescripcion))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Cerrar");
        jButton1.setBorder(null);
        jButton1.setDefaultCapable(false);
        jButton1.setFocusPainted(false);
        jButton1.setFocusable(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5))
                .addGap(0, 12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Expediente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Expediente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Expediente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Expediente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExpedienteInfo(new Expediente()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel area;
    private javax.swing.JLabel areaDescripcion;
    private javax.swing.JLabel asunto1;
    private javax.swing.JLabel asuntoDescripcion;
    private javax.swing.JLabel documentoDescripcion;
    private javax.swing.JLabel documentoReferencia1;
    private javax.swing.JLabel estadoActual;
    private javax.swing.JLabel estadoActualDescripcion;
    private javax.swing.JButton jButton1;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel tipoExpediente;
    private javax.swing.JLabel tipoExpedienteDescripcion;
    // End of variables declaration//GEN-END:variables
}
