/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import Enums.TipoDependencia;
import Utils.Utils;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.Timer;
import modelos.PersonaDependencia;

/**
 *
 * @author hecto
 */
public class LandingPersonal extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    PersonaDependencia trabajador;
    private Timer timer;
    private Timer expedienteTimer;

    public LandingPersonal(PersonaDependencia trabajador) {
        initComponents();
        setLocation(280, 50);
        this.setLocationRelativeTo(this);
        this.trabajador = trabajador;
        Utils.Setimage(jLabel1, "src/images/campus.jpg");
        Utils.Setimage(jLabel2, "src/images/logo.png");
        this.repaint();
        bienvenido.setFont(Servicio.FuenteServicio.fuentes.fuente(Servicio.FuenteServicio.fuentes.PoppinsBold, 1, 18));
        queDeseasHacer.setFont(Servicio.FuenteServicio.fuentes.fuente(Servicio.FuenteServicio.fuentes.PoppinsRegular, 0, 14));
        registrarExpediente.setFont(Servicio.FuenteServicio.fuentes.fuente(Servicio.FuenteServicio.fuentes.PoppinsRegular, 0, 14));

        universidadDeLima.setFont(Servicio.FuenteServicio.fuentes.fuente(Servicio.FuenteServicio.fuentes.PoppinsRegular, 0, 14));
        areaDe.setFont(Servicio.FuenteServicio.fuentes.fuente(Servicio.FuenteServicio.fuentes.PoppinsRegular, 0, 14));

        bienvenido.setText("¡Bienvenido de nuevo, " + trabajador.getNombre() + "!");
        areaDe.setText(TipoDependencia.fromEnumToString(trabajador.getTipoDepenedencia()));

        empezarHora();
        startExpedienteCheck();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        bienvenido = new javax.swing.JLabel();
        queDeseasHacer = new javax.swing.JLabel();
        universidadDeLima = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        verTodosLosExpedientes = new javax.swing.JButton();
        registrarExpediente = new javax.swing.JButton();
        areaDe = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        bienvenido.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bienvenido.setText("¡Bienvenido de nuevo, ! ");

        queDeseasHacer.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        queDeseasHacer.setText("¿Que deseas hacer hoy?");

        universidadDeLima.setText("Universidad de Lima");

        verTodosLosExpedientes.setBackground(new java.awt.Color(255, 102, 0));
        verTodosLosExpedientes.setForeground(new java.awt.Color(255, 255, 255));
        verTodosLosExpedientes.setText("Ver todos los expedientes");
        verTodosLosExpedientes.setBorder(null);
        verTodosLosExpedientes.setFocusPainted(false);
        verTodosLosExpedientes.setFocusable(false);
        verTodosLosExpedientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verTodosLosExpedientesActionPerformed(evt);
            }
        });

        registrarExpediente.setBackground(new java.awt.Color(255, 102, 0));
        registrarExpediente.setForeground(new java.awt.Color(255, 255, 255));
        registrarExpediente.setText("Registrar expediente");
        registrarExpediente.setBorder(null);
        registrarExpediente.setFocusPainted(false);
        registrarExpediente.setFocusable(false);
        registrarExpediente.setRequestFocusEnabled(false);
        registrarExpediente.setRolloverEnabled(false);
        registrarExpediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarExpedienteActionPerformed(evt);
            }
        });

        areaDe.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        areaDe.setText("Área de ");

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Salir");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Hora: ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bienvenido)
                    .addComponent(queDeseasHacer)
                    .addComponent(areaDe)
                    .addComponent(registrarExpediente, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(verTodosLosExpedientes, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(universidadDeLima)
                                .addGap(29, 29, 29)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(57, 57, 57))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(bienvenido)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(queDeseasHacer))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(universidadDeLima)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registrarExpediente, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(verTodosLosExpedientes, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(areaDe)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 840, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
     private void empezarHora() {

        timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

                SimpleDateFormat sdf = new SimpleDateFormat("HH:mm:ss");
                String currentTime = sdf.format(new Date());

                jLabel3.setText("Hora: " + currentTime);
            }
        });
        timer.start();
    }

    private void startExpedienteCheck() {

        expedienteTimer = new Timer(20000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                checkExpedientes();
            }
        });
        expedienteTimer.start();
    }

    private void checkExpedientes() {

        int cantidadExpedientes = Servicio.ExpedientesServicios.getExpedientesArea(this.trabajador.getTipoDepenedencia()).length;

        if (cantidadExpedientes > 0) {
            AlertaPrioridad alerta = new AlertaPrioridad();

            alerta.setSize(300, 200);
            alerta.setLocationRelativeTo(this);
            alerta.setVisible(true);
        }
    }
    private void registrarExpedienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarExpedienteActionPerformed
        System.out.println("Registrar expediente " + this.trabajador.getTipoDepenedencia());
        UserExpediente userExpediente = new UserExpediente(this.trabajador.getTipoDepenedencia());
        userExpediente.setVisible(true);
    }//GEN-LAST:event_registrarExpedienteActionPerformed

    private void verTodosLosExpedientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verTodosLosExpedientesActionPerformed
        PersonalExpedientes personalExpedientes = new PersonalExpedientes(this.trabajador);
        personalExpedientes.setVisible(true);
    }//GEN-LAST:event_verTodosLosExpedientesActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
        LandingPage main = new LandingPage();
        main.setVisible(true);

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LandingPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LandingPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LandingPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LandingPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LandingPersonal(new PersonaDependencia()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel areaDe;
    private javax.swing.JLabel bienvenido;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel queDeseasHacer;
    private javax.swing.JButton registrarExpediente;
    private javax.swing.JLabel universidadDeLima;
    private javax.swing.JButton verTodosLosExpedientes;
    // End of variables declaration//GEN-END:variables
}
