/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import Enums.TipoDependencia;
import Enums.TipoExpediente;
import java.io.IOException;
import java.time.LocalDateTime;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import modelos.Expediente;
import modelos.TiempoExpediente;
import modelos.User;

/**
 *
 * @author hecto
 */
public class UserExpediente extends javax.swing.JFrame {

    /**
     * Creates new form UserExpediente
     */
    private TipoDependencia dependencia;

    public UserExpediente(TipoDependencia dependencia) {
        initComponents();
        this.dependencia = dependencia;
        setLocation(280, 50);
        this.setLocationRelativeTo(this);
        DefaultComboBoxModel<String> comboBoxModel = new DefaultComboBoxModel<>();

        for (TipoExpediente tipo : TipoExpediente.values()) {
            comboBoxModel.addElement(TipoExpediente.fromEnumToString(tipo));
        }

        tipoExpediente1.setModel(comboBoxModel);

        DefaultComboBoxModel<String> comboBoxModel2 = new DefaultComboBoxModel<>();

        if (Servicio.UsersServicios.userCount > 0) {
            User[] usuarios = Servicio.UsersServicios.users;
            for (User user : usuarios) {
                comboBoxModel2.addElement(user.getCorreoElectronico());
            }

            User foundUser = Servicio.UsersServicios.users[Servicio.UsersServicios.users.length - 1];
            jCheckBox1.setText("Ultimo usuario creado (" + foundUser.getCorreoElectronico() + ")");
        }
        usuariosModel.setModel(comboBoxModel2);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jPanel2 = new javax.swing.JPanel();
        nuevoExpediente = new javax.swing.JLabel();
        usuariosModel = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        noDocumentoSeleccionado = new javax.swing.JLabel();
        elegirArchivo = new javax.swing.JButton();
        enviarRealizarNuevoExpediente = new javax.swing.JButton();
        EnviarExpediente = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        tipoExpediente1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        nuevoExpediente.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        nuevoExpediente.setForeground(new java.awt.Color(255, 102, 0));
        nuevoExpediente.setText("Realizar nuevo expediente");

        usuariosModel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("¿Cual es su solicitud?");

        jLabel3.setText("Asunto");

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane1.setViewportView(jTextArea2);

        noDocumentoSeleccionado.setText("No documento seleccionado");

        elegirArchivo.setBackground(new java.awt.Color(255, 102, 0));
        elegirArchivo.setForeground(new java.awt.Color(255, 255, 255));
        elegirArchivo.setText("Elegir archivo");
        elegirArchivo.setToolTipText("");
        elegirArchivo.setBorder(null);
        elegirArchivo.setDefaultCapable(false);
        elegirArchivo.setFocusPainted(false);
        elegirArchivo.setFocusable(false);
        elegirArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elegirArchivoActionPerformed(evt);
            }
        });

        enviarRealizarNuevoExpediente.setBackground(new java.awt.Color(102, 102, 102));
        enviarRealizarNuevoExpediente.setForeground(new java.awt.Color(255, 255, 255));
        enviarRealizarNuevoExpediente.setText("Enviar y hacer otra solicitud");
        enviarRealizarNuevoExpediente.setBorder(null);
        enviarRealizarNuevoExpediente.setBorderPainted(false);
        enviarRealizarNuevoExpediente.setDefaultCapable(false);
        enviarRealizarNuevoExpediente.setFocusPainted(false);
        enviarRealizarNuevoExpediente.setFocusable(false);
        enviarRealizarNuevoExpediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarRealizarNuevoExpedienteActionPerformed(evt);
            }
        });

        EnviarExpediente.setBackground(new java.awt.Color(0, 102, 255));
        EnviarExpediente.setForeground(new java.awt.Color(255, 255, 255));
        EnviarExpediente.setText("Enviar expediente");
        EnviarExpediente.setBorder(null);
        EnviarExpediente.setDefaultCapable(false);
        EnviarExpediente.setFocusPainted(false);
        EnviarExpediente.setFocusable(false);
        EnviarExpediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnviarExpedienteActionPerformed(evt);
            }
        });

        jLabel1.setText("Usuario");

        jCheckBox1.setText("Ultimo usuario creado (default@example.com)");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        tipoExpediente1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(noDocumentoSeleccionado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(elegirArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(enviarRealizarNuevoExpediente, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(EnviarExpediente, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jCheckBox1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nuevoExpediente)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(usuariosModel, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(tipoExpediente1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(nuevoExpediente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(68, 68, 68)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(noDocumentoSeleccionado)
                    .addComponent(elegirArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(usuariosModel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(jCheckBox1)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enviarRealizarNuevoExpediente, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EnviarExpediente, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(87, 87, 87)
                    .addComponent(tipoExpediente1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(447, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EnviarExpedienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnviarExpedienteActionPerformed
        enviar();
        dispose();
    }//GEN-LAST:event_EnviarExpedienteActionPerformed

    private void enviarRealizarNuevoExpedienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarRealizarNuevoExpedienteActionPerformed
        enviar();
        limpiarFormulario();

    }//GEN-LAST:event_enviarRealizarNuevoExpedienteActionPerformed
    java.io.File selectedFile = null;
    private void elegirArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elegirArchivoActionPerformed

        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Documentos", "doc", "docx", "pdf");
        fileChooser.setFileFilter(filter);

        int returnValue = fileChooser.showOpenDialog(null);

        if (returnValue == JFileChooser.APPROVE_OPTION) {
            selectedFile = fileChooser.getSelectedFile();
            noDocumentoSeleccionado.setText(selectedFile.getName());
        }
    }//GEN-LAST:event_elegirArchivoActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void enviar() {

        String tipoExpedienteValue = (String) tipoExpediente1.getSelectedItem();
        System.out.println("EXPEDIENTE" + tipoExpedienteValue);
        String asuntoValue = jTextArea2.getText();
        int prioridadValue;
        switch (TipoExpediente.fromStringToEnum(tipoExpedienteValue)) {
            case CERTIFICADO:
                prioridadValue = 2;
                break;
            case CONSTANCIA:
                prioridadValue = 2;
                break;
            case CARNET_UNIVERSITARIO:
                prioridadValue = 3;
                break;
            case LICENCIA:
                prioridadValue = 3;
                break;
            case RECLAMO:
                prioridadValue = 1;
                break;
            case AUTORIZACION:
                prioridadValue = 1;
                break;
            case HISTORIAL_ACADEMICO:
                prioridadValue = 2;
                break;
            default:
                prioridadValue = 0;
                break;
        }
        User foundUser;
        if (jCheckBox1.isSelected()) {
            foundUser = Servicio.UsersServicios.users[Servicio.UsersServicios.users.length - 1];

        } else {
            foundUser = Servicio.UsersServicios.obtenerUsuario((String) usuariosModel.getSelectedItem());
        }

        TiempoExpediente tiempoExpediente = new TiempoExpediente();
        tiempoExpediente.setFechaInicial(LocalDateTime.now());
        Expediente expedienteNuevo = new Expediente(Utils.Utils.generarIdentificador(), prioridadValue, TipoExpediente.fromStringToEnum(tipoExpedienteValue), this.dependencia, asuntoValue, foundUser, selectedFile, tiempoExpediente);
        expedienteNuevo.getAreas().encolar(this.dependencia);
        Servicio.ExpedientesServicios.agregarExpediente(expedienteNuevo);
        foundUser.agregarExpediente(expedienteNuevo);
    }

    private void limpiarFormulario() {
        tipoExpediente1.setSelectedIndex(0);
        usuariosModel.setSelectedIndex(0);
        jTextArea2.setText("");
        noDocumentoSeleccionado.setText("No documento seleccionado");
        selectedFile = null;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserExpediente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserExpediente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserExpediente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserExpediente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserExpediente(TipoDependencia.POR_ASIGNAR).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EnviarExpediente;
    private javax.swing.JButton elegirArchivo;
    private javax.swing.JButton enviarRealizarNuevoExpediente;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JLabel noDocumentoSeleccionado;
    private javax.swing.JLabel nuevoExpediente;
    private javax.swing.JComboBox<String> tipoExpediente1;
    private javax.swing.JComboBox<String> usuariosModel;
    // End of variables declaration//GEN-END:variables
}
