/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import Enums.TipoIdentificacion;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import modelos.User;

/**
 *
 * @author hecto
 */
public class UserRegister extends javax.swing.JFrame {

    /**
     * Creates new form User
     */
    public UserRegister() {
        initComponents();
        setLocation(280, 50);
        this.setLocationRelativeTo(this);
        DefaultComboBoxModel<String> comboBoxModel = new DefaultComboBoxModel<>();

        for (TipoIdentificacion tipo : TipoIdentificacion.values()) {
            comboBoxModel.addElement(TipoIdentificacion.fromEnumToString(tipo));
        }

        multipleChoiceUser.setModel(comboBoxModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        bienvenido = new javax.swing.JLabel();
        descripcion = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        nombre = new javax.swing.JLabel();
        fieldNombreUser = new javax.swing.JTextField();
        apellido = new javax.swing.JLabel();
        fieldApellidoUser = new javax.swing.JTextField();
        email = new javax.swing.JLabel();
        fieldEmailUser = new javax.swing.JTextField();
        DNI = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        fieldDniUser = new javax.swing.JTextField();
        identificacionUser = new javax.swing.JLabel();
        multipleChoiceUser = new javax.swing.JComboBox<>();
        iniciarSesionuSER = new javax.swing.JButton();
        email1 = new javax.swing.JLabel();
        contraseniaaUser = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        bienvenido.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bienvenido.setForeground(new java.awt.Color(255, 102, 0));
        bienvenido.setText("Registrar usuario");

        descripcion.setText("Antes de comenzar, es necesario que completes estos campos para poder registrar un expediente");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        nombre.setText("Nombre");

        fieldNombreUser.setForeground(new java.awt.Color(51, 51, 51));
        fieldNombreUser.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        fieldNombreUser.setToolTipText("Número de administrador");
        fieldNombreUser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        fieldNombreUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldNombreUserActionPerformed(evt);
            }
        });

        apellido.setText("Apellido");

        fieldApellidoUser.setForeground(new java.awt.Color(51, 51, 51));
        fieldApellidoUser.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        fieldApellidoUser.setToolTipText("Número de administrador");
        fieldApellidoUser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        fieldApellidoUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldApellidoUserActionPerformed(evt);
            }
        });

        email.setText("Email");

        fieldEmailUser.setForeground(new java.awt.Color(51, 51, 51));
        fieldEmailUser.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        fieldEmailUser.setToolTipText("Número de administrador");
        fieldEmailUser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        fieldEmailUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldEmailUserActionPerformed(evt);
            }
        });

        DNI.setText("DNI");

        jLabel1.setBackground(new java.awt.Color(102, 102, 102));
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("*Si es una institución omitir este campo");

        fieldDniUser.setForeground(new java.awt.Color(102, 102, 102));
        fieldDniUser.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        fieldDniUser.setToolTipText("Número de administrador");
        fieldDniUser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        fieldDniUser.setCaretColor(new java.awt.Color(255, 102, 0));
        fieldDniUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldDniUserActionPerformed(evt);
            }
        });

        identificacionUser.setText("Identificacion");

        multipleChoiceUser.setForeground(new java.awt.Color(102, 102, 102));
        multipleChoiceUser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elija una opción", "Persona", "Trabajdor", "dada" }));
        multipleChoiceUser.setBorder(null);
        multipleChoiceUser.setLightWeightPopupEnabled(false);
        multipleChoiceUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multipleChoiceUserActionPerformed(evt);
            }
        });

        iniciarSesionuSER.setBackground(new java.awt.Color(255, 102, 0));
        iniciarSesionuSER.setForeground(new java.awt.Color(255, 255, 255));
        iniciarSesionuSER.setText("Registrar");
        iniciarSesionuSER.setBorder(null);
        iniciarSesionuSER.setBorderPainted(false);
        iniciarSesionuSER.setFocusPainted(false);
        iniciarSesionuSER.setFocusable(false);
        iniciarSesionuSER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarSesionuSERActionPerformed(evt);
            }
        });

        email1.setText("Contraseña");

        contraseniaaUser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        contraseniaaUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contraseniaaUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombre)
                            .addComponent(apellido)
                            .addComponent(email)
                            .addComponent(email1))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldNombreUser)
                            .addComponent(fieldApellidoUser)
                            .addComponent(fieldEmailUser)
                            .addComponent(contraseniaaUser)))
                    .addComponent(jLabel1)
                    .addComponent(iniciarSesionuSER, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DNI)
                            .addComponent(identificacionUser))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(multipleChoiceUser, javax.swing.GroupLayout.Alignment.TRAILING, 0, 300, Short.MAX_VALUE)
                            .addComponent(fieldDniUser, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap(128, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldNombreUser, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombre))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldApellidoUser, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(apellido))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldEmailUser, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(email))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contraseniaaUser, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(email1))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldDniUser, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DNI))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(multipleChoiceUser, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(identificacionUser))
                .addGap(32, 32, 32)
                .addComponent(iniciarSesionuSER, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bienvenido)
                    .addComponent(descripcion))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(bienvenido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(descripcion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fieldNombreUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNombreUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldNombreUserActionPerformed

    private void fieldApellidoUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldApellidoUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldApellidoUserActionPerformed

    private void fieldEmailUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldEmailUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldEmailUserActionPerformed

    private void fieldDniUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldDniUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldDniUserActionPerformed

    private void iniciarSesionuSERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarSesionuSERActionPerformed
        try {
            String nombreValue = fieldNombreUser.getText();
            String apellidoValue = fieldApellidoUser.getText();
            String identificacion = (String) multipleChoiceUser.getSelectedItem();
            String correoElectronicoValue = fieldEmailUser.getText();
            String DNIUser = fieldDniUser.getText();
            String contrasenia = String.valueOf(contraseniaaUser.getPassword());

            if (nombreValue.equals("") || apellidoValue.equals("") || identificacion.equals("") || correoElectronicoValue.equals("")) {
                throw new IllegalArgumentException("Todos los campos son requeridos");
            }
            if (!Utils.Utils.esEmailValido(correoElectronicoValue)) {
                throw new IllegalArgumentException("Correo electrónico no válido");
            }
            User usuarioNuevo = new User(nombreValue, apellidoValue, correoElectronicoValue, contrasenia, TipoIdentificacion.fromStringToEnum(identificacion), DNIUser);

            Servicio.UsersServicios.agregarUsuario(usuarioNuevo);
            dispose();
            //mandar aviso
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_iniciarSesionuSERActionPerformed

    private void multipleChoiceUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multipleChoiceUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_multipleChoiceUserActionPerformed

    private void contraseniaaUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contraseniaaUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contraseniaaUserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserRegister().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DNI;
    private javax.swing.JLabel apellido;
    private javax.swing.JLabel bienvenido;
    private javax.swing.JPasswordField contraseniaaUser;
    private javax.swing.JLabel descripcion;
    private javax.swing.JLabel email;
    private javax.swing.JLabel email1;
    private javax.swing.JTextField fieldApellidoUser;
    private javax.swing.JTextField fieldDniUser;
    private javax.swing.JTextField fieldEmailUser;
    private javax.swing.JTextField fieldNombreUser;
    private javax.swing.JLabel identificacionUser;
    private javax.swing.JButton iniciarSesionuSER;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox<String> multipleChoiceUser;
    private javax.swing.JLabel nombre;
    // End of variables declaration//GEN-END:variables
}
